language: perl
perl:
- '5.16'
before_install:
- cpanm Carton
- cpanm Mojolicious
- cpanm Devel::Cover
- cpanm Devel::Cover::Report::Coveralls
install:
- cpanm --installdeps --notest . || cat ~/.cpanm/build.log
after_failure: 
- cat ~/.cpanm/build.log
script:
- HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" prove -lrv ./t
after_success:
- cover -report coveralls

